"""Create initial tables from models

Revision ID: 00881e9e4edf
Revises: 048a3f62b2c2
Create Date: 2026-06-30 13:57:34.468080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00881e9e4edf'
down_revision: Union[str, Sequence[str], None] = '048a3f62b2c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=True),
    sa.Column('google_sub', sa.String(length=64), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('image_file', sa.String(length=200), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'INFLUENCER', 'BRAND', name='userrole'), nullable=False),
    sa.Column('date_joined', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_sub'), 'users', ['google_sub'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_password_hash'), 'users', ['password_hash'], unique=False)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('brand_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=150), nullable=False),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('company_size', sa.String(length=50), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brand_profiles_user_id'), 'brand_profiles', ['user_id'], unique=True)
    op.create_table('influencer_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('niche', sa.Enum('TECH', 'GAMING', 'EDUCATION', 'FINANCE', 'FITNESS', 'FOOD', 'TRAVEL', 'ENTERTAINMENT', 'MUSIC', 'BEAUTY', 'BUSINESS', 'LIFESTYLE', 'SPORTS', 'NEWS', 'AUTOMOTIVE', 'OTHER', name='influencer_niche'), nullable=False),
    sa.Column('availability', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_influencer_profiles_niche'), 'influencer_profiles', ['niche'], unique=False)
    op.create_index(op.f('ix_influencer_profiles_user_id'), 'influencer_profiles', ['user_id'], unique=True)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_password_reset_tokens_id'), 'password_reset_tokens', ['id'], unique=False)
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_profile_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('budget_min', sa.Integer(), nullable=False),
    sa.Column('budget_max', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'CLOSED', 'COMPLETED', name='campaignstatus'), nullable=False),
    sa.Column('image_file', sa.String(length=200), nullable=True),
    sa.Column('date_posted', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_profile_id'], ['brand_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_brand_profile_id'), 'campaigns', ['brand_profile_id'], unique=False)
    op.create_index(op.f('ix_campaigns_id'), 'campaigns', ['id'], unique=False)
    op.create_index(op.f('ix_campaigns_status'), 'campaigns', ['status'], unique=False)
    op.create_table('social_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('influencer_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.Enum('instagram', 'youtube', 'tiktok', name='social_platform'), nullable=False),
    sa.Column('youtube_channel_id', sa.String(length=200), nullable=False),
    sa.Column('youtube_handle', sa.String(length=120), nullable=True),
    sa.Column('youtube_channel_name', sa.String(length=200), nullable=True),
    sa.Column('subscribers_count', sa.BigInteger(), nullable=True),
    sa.Column('total_views', sa.BigInteger(), nullable=True),
    sa.Column('total_videos', sa.Integer(), nullable=True),
    sa.Column('average_views', sa.BigInteger(), nullable=True),
    sa.Column('engagement_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['influencer_id'], ['influencer_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_accounts_influencer_id'), 'social_accounts', ['influencer_id'], unique=False)
    op.create_index(op.f('ix_social_accounts_platform'), 'social_accounts', ['platform'], unique=False)
    op.create_index(op.f('ix_social_accounts_youtube_channel_id'), 'social_accounts', ['youtube_channel_id'], unique=True)
    op.create_table('campaign_proposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('influencer_profile_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('proposed_budget', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'WITHDRAWN', name='proposalstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['influencer_profile_id'], ['influencer_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'influencer_profile_id', name='uq_campaign_influencer_proposal')
    )
    op.create_index(op.f('ix_campaign_proposals_campaign_id'), 'campaign_proposals', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_proposals_id'), 'campaign_proposals', ['id'], unique=False)
    op.create_index(op.f('ix_campaign_proposals_influencer_profile_id'), 'campaign_proposals', ['influencer_profile_id'], unique=False)
    op.create_index(op.f('ix_campaign_proposals_status'), 'campaign_proposals', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_campaign_proposals_status'), table_name='campaign_proposals')
    op.drop_index(op.f('ix_campaign_proposals_influencer_profile_id'), table_name='campaign_proposals')
    op.drop_index(op.f('ix_campaign_proposals_id'), table_name='campaign_proposals')
    op.drop_index(op.f('ix_campaign_proposals_campaign_id'), table_name='campaign_proposals')
    op.drop_table('campaign_proposals')
    op.drop_index(op.f('ix_social_accounts_youtube_channel_id'), table_name='social_accounts')
    op.drop_index(op.f('ix_social_accounts_platform'), table_name='social_accounts')
    op.drop_index(op.f('ix_social_accounts_influencer_id'), table_name='social_accounts')
    op.drop_table('social_accounts')
    op.drop_index(op.f('ix_campaigns_status'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_brand_profile_id'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_password_reset_tokens_id'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_influencer_profiles_user_id'), table_name='influencer_profiles')
    op.drop_index(op.f('ix_influencer_profiles_niche'), table_name='influencer_profiles')
    op.drop_table('influencer_profiles')
    op.drop_index(op.f('ix_brand_profiles_user_id'), table_name='brand_profiles')
    op.drop_table('brand_profiles')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_password_hash'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_google_sub'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
